services:
  client:
    build: ./client
    container_name: codevspace-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - yjs-server
    networks:
      - codevspace-network

  mongodb:
    image: mongo:latest
    container_name: codevspace-mongo
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - codevspace-network

  backend:
    build: backend/backend
    container_name: codevspace-backend
    ports:
      - "8080"
    depends_on:
      - mongodb
    networks:
      - codevspace-network
    env_file:
      - backend/backend/.env

  yjs-server:
    build: backend/backend/yjs-server
    container_name: codevspace-yjs
    expose:
      - "1234"
    networks:
      - codevspace-network
    env_file:
      - backend/backend/.env

networks:
  codevspace-network:
    driver: bridge

volumes:
  mongodb_data:



