spring.application.name=backend
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.mongodb.database=codevspace
spring.data.mongodb.auto-index-creation=true


application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=86400000

app.frontend.oauth2.redirect-uri=${OAUTH2_REDIRECT_URI}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email,read:user

app.judge0.url=${JUDGE0_URL}

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.forward-headers-strategy=framework