spring.application.name=backend
spring.mongodb.uri=mongodb+srv://codevspace_user:PYUlsqSADhZ1734P@cluster0.frgqlvt.mongodb.net/?appName=Cluster0
spring.mongodb.database=codevspace
spring.security.user.name=ankit
spring.security.user.password=0208
spring.data.mongodb.auto-index-creation=true
# A secure 256-bit (or larger) Base64 encoded secret key.
# DO NOT use this exact string in production! Generate your own secure string.
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Expiration time in milliseconds (86400000 = 1 day)
application.security.jwt.expiration=86400000

app.frontend.oauth2.redirect-uri=http://localhost:3000/oauth2/redirect

spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=
spring.security.oauth2.client.registration.github.scope=user:email,read:user

app.judge0.url=http://13.28.24.91:2358